### ISSUE TITLE
Enable configuration of workflows via a Hadoop JobConf XML

### ISSUE THREAD

**Issue by sprzedwojski** [GoogleCloudPlatform/oozie-to-airflow#115]
Many workflows, i.e. MapReduce, Pig can use this configuration option.

We need to handle the `<job-xml>[JOB-XML-FILE]</job-xml>` tag in the workflow, indication the conf file.

eg. https://oozie.apache.org/docs/5.1.0/WorkflowFunctionalSpec.html#a3.2.3_Pig_Action

**Comment by mik-laj** [comment]
I added support for this feature in my Spark Mapper, so we do not start from scratch.

**Comment by mik-laj** [comment]
Done in https://github.com/GoogleCloudPlatform/oozie-to-airflow/pull/282 ?

**Comment by sprzedwojski** [comment]
Yes, done in #282 :+1:
