### ISSUE TITLE
Remove unnecessary imports from generated DAGs

### ISSUE THREAD

**Issue by sprzedwojski** [GoogleCloudPlatform/oozie-to-airflow#116]
A lot of generated DAGs have unused imports.
It would be good to go through all of them and modify required imports in each mapper accordingly.

![image](https://user-images.githubusercontent.com/4280682/56721442-2dc80b80-6745-11e9-8c63-db0cf6a70f63.png)

**Comment by mik-laj** [comment]
Is this a bug or an enhancement proposal? I think that this is just an improvement.

**Comment by sprzedwojski** [comment]
"You say to-MAY-to, I say to-MAH-to" ;) 🍅 🍅 
Doesn't really matter how you label it, it should be done.
