### ISSUE TITLE
Serialization of data types in templates

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#121]
Hello,

In templates, we need to display Python types. The current solution works properly only for narrow cases.
For example:
```
{{ task_id }}_prepare = bash_operator.BashOperator(
    task_id='{{ task_id }}_prepare',
    bash_command='{{ prepare_command }}'
)
```
If the single quote character appears in the variable, we get the wrong Python code. When `task_id` = `AAA`,  `prepare_command` = `cat 'a'` then, we gets a code:
```python
AAA_prepare = bash_operator.BashOperator(
    task_id='AAA_prepare',
    bash_command='cat 'a''
)
```
This is not a valid Python code.

I proposed a much more stable solution in #102. I used the [`tojson`](http://jinja.pocoo.org/docs/2.10/templates/#tojson) filter to display parameter. 
For template:
```
{{ task_id }}_prepare = bash_operator.BashOperator(
    task_id='{{ task_id }}_prepare',
    bash_command={{ prepare_command | tojson }}
)
```
when `task_id` = `AAA`,  `prepare_command` = `cat "a"` then, we gets a code:
```python
AAA_prepare = bash_operator.BashOperator(
    task_id='AAA_prepare',
    bash_command="cat \"a'\"
)
```
This solution is also correct for more complex types.  When `task_id` = `AAA`,  `prepare_command` = `['cat "a"', 'cat "a"']` (list[str]) then, we gets a code:
```python
AAA = bash_operator.BashOperator(
    task_id='AAA',
    bash_command=["cat \"a\"", "cat \"a\""]
)
```
But this solution does not work for more complex data structures, ex. `None`, boolean values.

I would be joyous and happy if it would also work for these data types.  To do this, you must write your own simple type serialiser that returns a Python-compatible code and create a Jinja filter.

Thanks

**Comment by mik-laj** [comment]
@potiuk @sprzedwojski WDYT?

**Comment by sprzedwojski** [comment]
From the BashOperator’s docstring:
> The command, set of commands or reference to a
>    bash script (must be '.sh') to be executed.

Correct me if I’m wrong, but from this I guess the `bash_command` can only be a string or a list of strings.
Therefore from what you wrote it seems that the `to_json` filter would be enough, wouldn’t it?

Szymon Przedwojski
Polidea | Software Engineer

M: +48 500 330 790
E: szymon.przedwojski@polidea.com

**Comment by mik-laj** [comment]
All operators that we currently use do not need other types than string or list.
However, other operators also require boolean values.
SparkSubmitOperator > verbose
https://airflow.apache.org/_api/airflow/contrib/operators/spark_submit_operator/index.html
None is also a value that may appear sometime in the future, but it is difficult to find a specific situation right now.

**Comment by sprzedwojski** [comment]
But in the case of `verbose` we could just have:
```
verbose={{verbose_val}},
```

and it would render to, e.g.:
```
verbose=True,
```
right?

**Comment by potiuk** [comment]
I think indeed trying to get a super- general solution for this problem is a bit too far fetched. It seems a bit artificial. Just the right combination of careful, well written templates and proper values types passed should do the job well.

**Comment by mik-laj** [comment]
Do you agree that it is worth updating previous mappers to use tojson filter?

**Comment by potiuk** [comment]
Sure. That's what 'carefully written templates' mean
