### ISSUE TITLE
Trigger rules and multiple tasks (0/5)

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#131]
Hello

Triggering rules take incorrect values in error when the mapper has multiple tasks.

Currently, trigger rules for all tasks are identical. Also when it serves to handle the error flow.

The first task should have changed trigger rules.  The other tasks should have trigger rules set to the default value.

Thanks

**Comment by sprzedwojski** [comment]
Note from a similar issue:

Right now the mappers' constructor accepts a TriggerRule value, which is then completely ignored.
Instead there's an update_trigger_rules() method in parser, which sets them according to whether the particular task is a fail task (ONE_FAILED), any other task (ONE_SUCCESS, although it should rather be ALL_SUCCESS) or when it can't be determined which type a task is, it's set to DUMMY.

One approach would be to completely remove the constructor setting of the trigger rules and rely comletely on the update_trigger_rules() method.

However other ideas are welcome.
