### ISSUE TITLE
Implement a sample wf:function

### ISSUE THREAD

**Issue by potiuk** [GoogleCloudPlatform/oozie-to-airflow#156]

**Comment by mik-laj** [comment]
Hello,
Today we had a meeting about how to implement this functionality.
Notes are available
https://hackmd.io/T0YBhLtRSZCbx49GtMtNxQ
Thanks,

**Comment by sprzedwojski** [comment]
Today we discussed this and decided to change the objective from supporting all wf:functions to instead implementing a sample wf:function only. It will demonstrate how to access data from the Airflow database inside the function.

Apart from that, we'll describe it in the CONTRIBUTING documentation.

This way if anyone intends to implement the remaining wf:functions they'll have a tangible example and instructions on how to do so.
