### ISSUE TITLE
Issues and pull request  templates (0/0.5)

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#176]
Hello,

Currently, issues and PR have different levels of detail in descriptions. It would be useful to introduce templates, which will increase the quality of the descriptions.

https://help.github.com/en/articles/about-issue-and-pull-request-templates

Thanks

**Comment by potiuk** [comment]
I noticed that "Community" section in Github had ready-to-use templates for bugs and new feature requests. I adapted it a bit and created a #191 issue and corresponding PR
