### ISSUE TITLE
TestOozieExamples and properties

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#177]
Hello,

Stores properties as a dictionary in the test code. At the same time, the properties are specified separately in the file. This makes this test difficult to maintain. It would be nice if this test read the properties from files.
https://github.com/GoogleCloudPlatform/cloud-composer/blob/94b8a28/oozie-to-airflow/tests/converter/test_oozie_parser.py#L402-L527

Thanks

**Comment by potiuk** [comment]
I disagree. I think tests should be mostly self-contained in the .py file so that you can see test data and code in the unit tests. We can discuss it though.

**Comment by mik-laj** [comment]
I also agree, but these are integration tests that check the correctness of processing specific examples from specific catalogs. The goal is to test a more complex process on data close to real data. This data is part of the repository and is the best source for this test. In this case, it is worth ensuring that this particular test reads all data from the source, not just the part.

**Comment by mik-laj** [comment]
@sprzedwojski Do you think that this issues is still valid?

**Comment by sprzedwojski** [comment]
Not sure, we could probably discuss this.
