### ISSUE TITLE
Fix class variables in a number of classes (0/0.5)

### ISSUE THREAD

**Issue by potiuk** [GoogleCloudPlatform/oozie-to-airflow#180]
In a number of classes (Parser for example) we use class-level variables rather than object variables (and set them in self). We need to remove those usages.

**Comment by mik-laj** [comment]
```python
class MyTestItem:
    name: str
    def __init__(self, name):
        self.name = name

my_item_1 = MyTestItem("AAA")
my_item_2 = MyTestItem("BBB")

print(my_item_1.name)
print(my_item_2.name)
```
Output:
```
AAA
BBB
```
You showed an example similar to that. This example works fine.
The problem is when there is an object initialized at the class level. Object is shared between all instances.
Example:
```python
class MyTestItem:
    name: str = []
    def __init__(self, name):
        self.name.append(name)

my_item_1 = MyTestItem("AAA")
my_item_2 = MyTestItem("BBB")

print(my_item_1.name)
print(my_item_2.name)
```
Output:
```
['AAA', 'BBB']
['AAA', 'BBB']
```
I saw this one case and tried to fix it in this PR:
https://github.com/GoogleCloudPlatform/cloud-composer/pull/166

**Comment by potiuk** [comment]
It works only because MyTestItem.name is actually completely different object than self.name in this case. See https://stackoverflow.com/questions/68645/are-static-class-variables-possible where this is discussed at-length.

Simply speaking, this is completely misleading because name: str is declaration of a different variable than self.name. It does not even tell what the type of self.name is because these are two different variables (one is class-level, and the other is instance level):

```
class MyTestItem:
    name: str
    def __init__(self, name):
        self.name = name
``` 

In the example above MyTestItem.name is an 'str' class-level variable but self.name is 'unknown type' instance variable.

The correct ways of declaring the type of instance variable is:

```
class MyTestItem:
    def __init__(self, name: str):
        self.name = name
``` 
or 

```
class MyTestItem:
    def __init__(self, name):
        self.name : str = name
``` 
So my proposal is that we (as soon as the current refactoring of Jinja templates is done) fix it in all places and only leave the NamedTuple declarations in that "class-level" form as it is fairly convenient there. 

@sprzedwojski @mik-laj @antonimaciej -let me know what you think.

**Comment by potiuk** [comment]
Ideally we should also see if any of the tools we use (pylint/mypy or others) can detect such cases and prevent us from making similar mistakes in the future.
