### ISSUE TITLE
Samples for EL functions

### ISSUE THREAD

**Issue by sprzedwojski** [GoogleCloudPlatform/oozie-to-airflow#195]
Expand the current sample workflows to cover at least one EL function from each category: basic, workflow, and action.

**Comment by mik-laj** [comment]
```
```
${fs:fileSize('/usr/foo/myinputdir') gt 10 * GB}
${nameNode}/user/${wf:user()}/${examplesRoot}/output-data/${outputDir}
${hadoop:counters("mr-node")["FileSystemCounters"]["FILE_BYTES_READ"]}
${hadoop:counters("pig-node")["JOB_GRAPH"]}
${wf:actionData('shell-node')['my_output'] eq 'Hello Oozie'}
${(hadoop:counters("mr-node")[RECORDS][MAP_IN] == hadoop:counters("mr-node")[RECORDS][MAP_OUT]) and (hadoop:counters("mr-node")[RECORDS][REDUCE_IN] == hadoop:counters("mr-node")[RECORDS][REDUCE_OUT]) and (hadoop:counters("mr-node")[RECORDS][GROUPS] gt 0)}
${coord:dataOut('output')}
Lubie Placki ${coord:user()}
${coord:current(0)}
${YEAR}/${MONTH}/${DAY}/${HOUR}
${coord:offset(-42, "MINUTE")}
${(wf:actionData('java1')['datelist'] == EXPECTED_DATE_RANGE)}
${fs:exists(concat(concat(concat(concat(concat(nameNode, '/user/'), wf:user()), '/'), examplesRoot), '/output-data/demo/mr-node')) == "true"}
${wf:actionData('getDirInfo')['dir.num-files'] gt 23 || wf:actionData('getDirInfo')['dir.age'] gt 6}
${fs:exists(wf:actionData('hdfs-lookup')['outputPath']/2)}
${wf:actionData('shell-node')['my_output'] eq 'Hello Oozie'}
${1 > (4/2)}
${4.0 >= 3}
${100.0 == 100}
${(10*10) ne 100}
${'a' < 'b'}
${'hip' gt 'hit'}
${4 > 3}
${1.2E4 + 1.4}
${3 div 4}
${10 mod 4}
${pageContext.request.contextPath}
${sessionScope.cart.numberOfItems}
${param['mycom.productId']}
${header["host"]}
${departments[deptName]}
${requestScope['javax.servlet.forward.servlet_path']}
#{customer.lName}
#{customer.calcTotal}
${wf:conf("jump.to") eq "ssh"}
${wf:conf("jump.to") eq "parallel"}
${wf:conf("jump.to") eq "single"}
```
```
