### ISSUE TITLE
Access to Web UI of Oozie (0/0.5)

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#206]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to connect to Oozie's Web UI. it is not directly accessible from local computer or by [Compontent Gateway](https://cloud.google.com/dataproc/docs/concepts/accessing/dataproc-gateways).

**Describe the solution you'd like**
I use a shell script:
```
#!/bin/bash
set +x

HOSTNAME=oozie-o2a-2cpu-m
PROJECT=polidea-airflow
ZONE=europe-west3-c
PORT=8033

gcloud compute ssh ${HOSTNAME} --project=${PROJECT} --zone=${ZONE}  -- -D ${PORT} -N &
 "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --proxy-server="socks5://localhost:${PORT}" --user-data-dir=/tmp/${HOSTNAME} http://${HOSTNAME}:11000
rm -rf /tmp/${HOSTNAME}
kill %1
```
This script could become part of the `run-sys-test`. This will be a similar option as the `-S` option

**Describe alternatives you've considered**
N/A

**Additional context**
Oozie has a Web GUI, but unfortunately it is only available locally from the virtual machine. You must use port forwarding to access there.

**Comment by potiuk** [comment]
Which milestone? Shall we plan it for Bravo :)?

**Comment by mik-laj** [comment]
I do not know. We must meet at the meeting planning to determine.
