### ISSUE TITLE
Pylint  no-name-in-module error disabled

### ISSUE THREAD

**Issue by potiuk** [GoogleCloudPlatform/oozie-to-airflow#241]
**Describe the bug**
We had to disable pylint no-name-in-module check because it was mysteriously failing. We need to investigate and fix it and re-enable the check.

**To Reproduce**

1. remove  no-name-in-module from pylintrc
2. run `pre-commit run pylint --all-files`
3. observe errors produced by pylint

**Expected behavior**
Pylint should produce no errors with no-name-in-module enabled.

**Comment by nuclearpinguin** [comment]
I removed the `no-name-in-module` and running `pre-commit run --all-files` resulted in full pass.

**Comment by nuclearpinguin** [comment]
Ok, so the issue came back when I started refactor. The reason seems to be the `__init__.py` file in `o2a`:
```python
# ..
# See the License for the specific language governing permissions and
# limitations under the License.
"""Oozie-to-Airflow converter"""
NAME = "o2a"
```

When I remove the 'name' line the error disappears. What is the purpose of the line?
