### ISSUE TITLE
CONFG dict is empty in Generated DAG , have changed the configuration.template.properties to configuration.properties

### ISSUE THREAD

**Issue by piyush09-kl** [GoogleCloudPlatform/oozie-to-airflow#247]

**Comment by piyush09-kl** [comment]
Please check the o2a/converter/oozie_converter.py  , setting self.params before parsing the config file i think.

**Comment by mik-laj** [comment]
Can you provide more information?

I think a command similar to the one below should install the project correctly.
```bash
git clone https://github.com/GoogleCloudPlatform/oozie-to-airflow.git
pip install -r requirements.txt
sudo apt-get install coreutils libxml2-utils
./bin/o2a-run-all-conversions
```

**Comment by mik-laj** [comment]
```
curl https://raw.githubusercontent.com/GoogleCloudPlatform/oozie-to-airflow/master/o2a/converter/oozie_converter.py -s | grep params
```
It does not give any results.

**Comment by potiuk** [comment]
I think you are fixing it already @mik-laj in your branch for error rules. I reassigned it to you :)

**Comment by mik-laj** [comment]
Closed by: https://github.com/GoogleCloudPlatform/oozie-to-airflow/pull/262
