### ISSUE TITLE
Introduce transformer concept

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#256]
**Is your feature request related to a problem? Please describe.**
I'm always happy when I working on refactor trigger rules. However, I miss a certain mechanism that will improve the implementation of this functionality. 

**Describe the solution you'd like**
Currently, there is one mechanism for adjusting the workflow - `on_parse_finished` in mappers. 
However, this is very problematic for several reasons:
* It is not possible to control the order in which these operations are performed. They are always performed according to the order of nodes.
* It is always associated with a single mappera. It is not possible to create general transformations.
* the principle of one responsibility is broken. Mapper performs conversion of the node into relations and tasks, but also transforms the workflow to provide various other functionalities.

I propose to create a separate mechanism that will perform the appropriate transformations.  Transformaers will be the oozie_converter parameter, so it will be possible to conditionally perform specific transformations. Transformations will be performed at the place of the previous on_parse_finish execution
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/0d3b2d6/o2a/converter/oozie_converter.py#L100-L101

**Describe alternatives you've considered**
We can hold all information as static methods in the same class.

**Additional context**
I can attach the current implmentation based on static methods
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/1942143005ea7c24a2c3f09d9a23874d25787fa9/o2a/converter/oozie_converter.py

**Comment by potiuk** [comment]
After discussing it this morning - I like the concept! We should try to explain it today (if we have time) to Feng and we should implement it. It will make triggering rules implementation much more straightforward.

**Comment by potiuk** [comment]
Let's plan it for Beta if Feng will be ok with it.

**Comment by mik-laj** [comment]
Done via: https://github.com/GoogleCloudPlatform/oozie-to-airflow/pull/259
