### ISSUE TITLE
Implement Email mapper

### ISSUE THREAD

**Issue by potiuk** [GoogleCloudPlatform/oozie-to-airflow#26]
Reference: https://oozie.apache.org/docs/5.1.0/DG_EmailActionExtension.html

**Comment by mik-laj** [comment]
Reference: https://oozie.apache.org/docs/5.1.0/DG_EmailActionExtension.html

**Comment by potiuk** [comment]
We implement no-attachment version.

**Comment by sprzedwojski** [comment]
Instructions on how the MailHog test SMTP server is being run: https://hackmd.io/@spr/HJFYU-qlr

**Comment by mik-laj** [comment]
Are you planning to report a problem with setting the SMTP password to Composer team? Do you think it's worth do it?

**Comment by sprzedwojski** [comment]
Haven't thought of it but it might be a good idea actually.
