### ISSUE TITLE
Rename OozieParser to WorkflowXmlParser

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#263]
**Describe the bug**
I am always frustrated when classes have bad names
I think that the `OozieParser` class should be called `WorkflowXmlParser`. This will better describe her roles and allow easier understanding of the code.
When this change is made, this application will not apply.
https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/177

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by LeonardoFurtado** [comment]
I will try do it!

**Comment by mik-laj** [comment]
@LeonardoFurtado Awesome. I am waiting for your PR. :-D
