### ISSUE TITLE
TestOozieExamples should contain more assertions

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#264]
**Is your feature request related to a problem? Please describe.**
One of the classes has tests that do not have enough assertions to prevent full regression.
This test to `TestOozieExamples`.

**Describe the solution you'd like**
I would be happy if the assertions check the existence of `ParsedActionNodes` object in `Workflow` object...and field `downstream_names` and `error_xml` in `ParsedActionNodes` objects.
Currently only the first one is checked.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LeonardoFurtado** [comment]
@mik-laj The test needs check if `error_xml` is None and if `downstream_names` is empty?

**Comment by mik-laj** [comment]
tests should check the equality. 
```
self.assertEquals(["node-a"], node.downstream_names)
self.assertEquals("error-node", node.error_xml)
```

**Comment by mik-laj** [comment]
The existence of this test prevents regression in the project.

**Comment by LeonardoFurtado** [comment]
So, I'm few confused, I never used Parameterized before, but i liked how it works . In `test_parse_workflow_examples` i can use `current_parser.workflow.nodes` to return all nodes, and i can use `current_parser.workflow.nodes[node]` (using for statement maybe?) to receive `downstream_names` and `error_xml` of workflow object, I believe both will be used as the second parameter of assertEqual . But I don't understand how I will get the first parameter of assertEqual in this case. Am I thinking the wrong way?

**Comment by LeonardoFurtado** [comment]
```python
for node in current_parser.workflow.nodes:
            self.assertEqual(?, current_parser.workflow.nodes[node].downstream_names)
```
My main question is whether this should be done that way.

**Comment by mik-laj** [comment]
Will it be fine for you if it prepares a test code for you for one case and you will complete it for the rest?

**Comment by LeonardoFurtado** [comment]
i think so

**Comment by mik-laj** [comment]
My commit is available here:
https://github.com/GoogleCloudPlatform/oozie-to-airflow/tree/update-test-oozie-exampple

**Comment by LeonardoFurtado** [comment]
Thanks, I'll see it!

**Comment by LeonardoFurtado** [comment]
@mik-laj  you can look at [this](https://github.com/LeonardoFurtado/oozie-to-airflow/blob/add-more-assertions-testoozie/tests/converter/test_workflow_xml_parser.py)? I need to know if it's okay to structure this way. The tests ran normally for `decision`,` demo` and `el`. Tell me if anything needs to be changed.

**Comment by mik-laj** [comment]
Can you create a PR? Then it will be easier for me to download your changes

**Comment by mik-laj** [comment]
Good direction! It looks good, but I have some comments:
1. Can you delete a venv from this commit? I use this project to manage the environment: https://virtualenvwrapper.readthedocs.io/en/latest/
2. Can you delete the WorkflowTestCase class?
3. Can you delete the node_names property from the WorkflowExpectedResult class?
3. Can you check the code using the `pre-commit` app?
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/master/CONTRIBUTING.md#static-code-analysis-and-pre-commit-hooks
It's a good idea to create a PR when you start work. It would also make it easier to add comments.

**Comment by LeonardoFurtado** [comment]
> Good direction! It looks good, but I have some comments:
> 
>     1. Can you delete a venv from this commit? I use this project to manage the environment: https://virtualenvwrapper.readthedocs.io/en/latest/
Sorry for this mistake, I must have run `git add .` probably.
>     2. Can you delete the WorkflowTestCase class?
Done
>     3. Can you delete the node_names property from the WorkflowExpectedResult class?
Done
>     4. Can you check the code using the `pre-commit` app?
>        https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/master/CONTRIBUTING.md#static-code-analysis-and-pre-commit-hooks
Done
>        It's a good idea to create a PR when you start work. It would also make it easier to add comments.
I will do that from now on. Thanks for feedback
