### ISSUE TITLE
SubWorkflow is not transformed

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#266]
**Describe the bug**
SubWorkflow is not transformed by transformers, because OozieConverter in SubworfklowMapper does not receive transformers.

**To Reproduce**
Start the conversation process and look at the diagram.
https://o2a-build-artifacts.storage.googleapis.com/commit-c04952ddc8354bcafa340703b30f7ff33f844f4e/output-dot/subwf/subdag_pig.png

**Expected behavior**
The start and end nodes should disappear.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by LeonardoFurtado** [comment]
`SubworfklowMapper` is not getting a Transformer List parameter to be added in `_parse_oozie_node()`. so, from where will the list of transformers be obtained? The only place where I see a list of tranformers was in `o2a.py` where you have something like this:
```python
    transformers = [
        RemoveInaccessibleNodeTransformer(),
        RemoveEndTransformer(),
        RemoveKillTransformer(),
        RemoveStartTransformer(),
        RemoveJoinTransformer(),
        RemoveForkTransformer(),
    ]
```
I looked at the other parameters of `SubworkflowMapper`to see if any of them had a Transformers list-type attribute, but I did not find any.
I believe the flow that needs to be followed when this change is made is this::
 `converter.convert()` -> `apply_transformers()` -> `process_workflow()` -> `remove_node()`
Tell if I am wrong.

**Comment by mik-laj** [comment]
You should give him a list by the constructor. I do not understand why the remove_node method is  associated with ypur proposition.

You should make changes to the following lines:
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/d25fb174ce0a49292c0ea3d65c187895e207cf23/o2a/converter/oozie_converter.py#L81
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/d25fb174ce0a49292c0ea3d65c187895e207cf23/o2a/converter/workflow_xml_parser.py#L54
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/d25fb174ce0a49292c0ea3d65c187895e207cf23/o2a/converter/workflow_xml_parser.py#L60
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/d25fb174ce0a49292c0ea3d65c187895e207cf23/o2a/converter/workflow_xml_parser.py#L215
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/d25fb174ce0a49292c0ea3d65c187895e207cf23/o2a/mappers/subworkflow_mapper.py#L49
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/d25fb174ce0a49292c0ea3d65c187895e207cf23/o2a/mappers/subworkflow_mapper.py#L60
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/d25fb174ce0a49292c0ea3d65c187895e207cf23/o2a/mappers/subworkflow_mapper.py#L77
