### ISSUE TITLE
Implement Sqoop mapper

### ISSUE THREAD

**Issue by potiuk** [GoogleCloudPlatform/oozie-to-airflow#27]
Reference: https://oozie.apache.org/docs/5.1.0/DG_SqoopActionExtension.html

**Comment by mik-laj** [comment]
Currently, Dataproc does not support sqoop, but our friend @szewi has prepared the appropriate PR.
https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/465

**Comment by sprzedwojski** [comment]
Great, I've just left a [comment there](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/465#issuecomment-495353304) asking for the PR to be merged in the near future.
