### ISSUE TITLE
Publish documentation about conversion process

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#274]
**Is your feature request related to a problem? Please describe.**
WIP

**Describe the solution you'd like**
WIP

**Describe alternatives you've considered**
WIP.

**Additional context**
WIP

**Comment by sprzedwojski** [comment]
Published at https://docs.google.com/document/d/1DmXn7iAj0H0eekiPBCDTH_VgN4jC8wWF7N-XLkejNj0/edit#heading=h.b48kcm9s7ymv
