### ISSUE TITLE
Add support for Workflow Job Status Notification

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#278]
**Is your feature request related to a problem? Please describe.**
It's part of https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/271

> If the oozie.wf.workflow.notification.url property is present in the workflow job properties when submitting the job, Oozie will make a notification to the provided URL when the workflow job changes its status. 

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
https://oozie.apache.org/docs/5.1.0/WorkflowFunctionalSpec.html#a5.1_Workflow_Job_Status_Notification

**Comment by sprzedwojski** [comment]
Done in #280
