### ISSUE TITLE
Add support for Node Start and End Notifications

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#279]
**Is your feature request related to a problem? Please describe.**
It's part of https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/271

> If the oozie.wf.action.notification.url property is present in the workflow job properties when submitting the job, Oozie will make a notification to the provided URL every time the workflow job enters and exits an action node.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
https://oozie.apache.org/docs/5.1.0/WorkflowFunctionalSpec.html#a5.2_Node_Start_and_End_Notifications

**Comment by sprzedwojski** [comment]
https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/271#issuecomment-507378149
