### ISSUE TITLE
Pytest unit tests start to take too much time on pre-commit

### ISSUE THREAD

**Issue by potiuk** [GoogleCloudPlatform/oozie-to-airflow#317]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to wait for pytest tests on commit. We have a lot of tests and some of them are a bit slow (integration level ones).

**Describe the solution you'd like**
Move pytest to pre-push only (pre-commit can still run all others).

**Describe alternatives you've considered**
* Remove pytest from pre-commit/pre-push altogether and leave it up to Travis. Not really good idea - the tests take maybe 10 seconds now
* Split the tests to fast/slow and run only fast ones in pre-commit and all in pre-push. We might implement it in the future as part of #174

**Comment by sprzedwojski** [comment]
Yasss! I also grew more and more frustrated about the tests being so long in pre-commit.
Both solutions sound good to me! 👌
