### ISSUE TITLE
Introduce extractor concept

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#322]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the structure of the code is unstructured. 

**Describe the solution you'd like**
I propose to introduce a extractor concept. 
The extractor will be responsible for processing XML elements into Python structures. In the meantime, it will also translate the EL expression into Jinja expression. In my opinion, all extractors should be stateless, so it should be function.

I am proposing the following steps:
1. Create a `o2a.extractors` module
2. Move a following files to this module:
```
o2a/utils/config_extractors.py
o2a/utils/file_archive_extractors.py
o2a/utils/param_extractor.py
```
3. Move the following methods to the new module `o2a/utils/primitives_extractor.py` and change their names:
```
o2a/utils/xml_utils/get_tag_el_text => extract_text_from_node
o2a/utils/xml_utils/get_tags_el_array_from_text => extract_list_string_from_node
```
4. Rewrite the following classes to be functions:
```
o2a.utils.file_archive_extractors.ArchiveExtractor
o2a.utils.file_archive_extractors.FileExtractor
```
Additionally, these classes do not need to store the state, so they will be more readable as functions. This is also simplify their logic.
In particular, the method `ArchiveExtractor. parse_node`. It should return one value. The result of the function should be determined by the parameter and not by assigning one or second method result.
Example of usage ArchiveExtractor:
Before
```python
archive_extractor = ArchiveExtractor(oozie_node=oozie_node, props=self.props)
_, hdfs_archive = archive_extractor.parse_node()
```
After:
```python
extract_archives_from_aoozie_nodes(oozie_node=self.oozie_node, as_hdfs=True, props=self.props)
```
**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nuclearpinguin** [comment]
>  In my opinion, all extractors should be stateless, so it should be function.

I wholeheartedly support the idea of stateless extractors.

**Comment by potiuk** [comment]
Absolutely!
