### ISSUE TITLE
Implement decision node (0/2)

### ISSUE THREAD

**Issue by sprzedwojski** [GoogleCloudPlatform/oozie-to-airflow#42]
When WF functions are ready.

**Comment by mik-laj** [comment]
I can see that the mapper is already in the repository. Can you expand the description of this issues? The key matter that should be included in the issues include:
* Description of current behavior;
* Description of expected behavior.

**Comment by sprzedwojski** [comment]
Yes, this issue was created quickly in the past as a reminder - I agree it could be more detailed.

The key thing here is to map the wf:function used as the decision action's condition to the correct Python function from `o2a_libs` - which will be in the DAG.

Currently in the example we only use the `firstNotNull` function as a dummy replacement.
