### ISSUE TITLE
 No module named 'o2a'

### ISSUE THREAD

**Issue by brubom** [GoogleCloudPlatform/oozie-to-airflow#497]
Probably I'm missing something, but I can't run any o2a converted DAG on Composer Airflow. I get same error every time:  No module named 'o2a'

I tried to add o2a package as a pypi package on composer, but it can't find it.

What am I missing?

**Comment by potiuk** [comment]
Just follow the docs: https://github.com/GoogleCloudPlatform/oozie-to-airflow#the-o2a-libraries

**Comment by brubom** [comment]
I end up doing that, but also was required to install lark-parser pypi package.

**Comment by CYarros10** [comment]
I also faced an error in Composer that required a lark package
