### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by turbaszek** [GoogleCloudPlatform/oozie-to-airflow#512]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to use Travis. Github Actions provide better experience in my opinion. 

**Describe the solution you'd like**
Use Github Actions to run static checks and tests as separate steps.

**Describe alternatives you've considered**
Jenkins ¯\_(ツ)_/¯ 

**Additional context**
N/A

**Comment by potiuk** [comment]
+1
