### ISSUE TITLE
Failure during validation

### ISSUE THREAD

**Issue by bluermind** [GoogleCloudPlatform/oozie-to-airflow#576]
**Describe the bug**
I have successfully installed o2a using pip.
I have copied my oozie workflow files according to the [recommended structure](https://github.com/GoogleCloudPlatform/oozie-to-airflow#structure-of-the-application-folder)

**To Reproduce**

1. Run `o2a -i /path/to/oozie_src -o /path/to/airflowdag`
2. It fails during the validation
```
/path/to/oozie_src/hdfs/workflow.xml:1: element workflow-app: Schemas validity error : Element '{uri:oozie:workflow:0.4}workflow-app': No matching global declaration available for the validation root.
```

[Edited]
To be more specific in reproducing the error, I've tried it with the sample workflow which I downloaded from https://raw.githubusercontent.com/mladkov/sample-oozie/master/wf/sample-oozie/workflow.xml 
Copied the file into a path named ~/sampledag/oozie/hdfs/workflow.xml
And ran `o2a -i ./oozie -o ./sample`. 
This produces the same error.
Below is more verbose record of the error message
```
[2020-09-28 18:36:09,489] {o2a.py:53} INFO - Found o2a-validate-workflows script at /home/bluermind/.local/bin/o2a-validate-workflows. Validating workflow

Validating ./oozie/hdfs/workflow.xml

./oozie/hdfs/workflow.xml:1: element workflow-app: Schemas validity error : Element '{uri:oozie:workflow:0.4}workflow-app': No matching global declaration available for the validation root.
./oozie/hdfs/workflow.xml fails to validate


Some workflows failed validation:

./oozie/hdfs/workflow.xml


[2020-09-28 18:36:09,632] {o2a.py:92} ERROR - Workflow failed schema validation. Please correct the workflow XML and try again.
```

**Expected behavior**
Validate successfully or provide a more detailed version of how the xml is invalid

**Desktop (please complete the following information):**
- OS: Amazon Linux 2

**Comment by turbaszek** [comment]
I'm afraid that we support only workflows using `uri:oozie:workflow:1.0` schema:

> The program targets Apache Airflow >= 1.10 and Apache Oozie 1.0 XML schema.
